version: '2'
services:
  zoo1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      MYID: 1
      SERVERS: zoo1,zoo2,zoo3
  zoo2:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
    environment:
      MYID: 2
      SERVERS: zoo1,zoo2,zoo3
  zoo3:
    image: wurstmeister/zookeeper
    ports:
      - "2183:2181"
    environment:
      MYID: 3
      SERVERS: zoo1,zoo2,zoo3

  broker1: 
    image: wurstmeister/kafka
    container_name: broker1
    ports:
      - "9092:9092"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_LOG_DIRS: /var/log/kafka
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: BTC:1:3,ETH:1:3
      KAFKA_ADVERTISED_HOST_NAME: docker-nitrohsu.com
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181
    restart: always
  broker2: 
    image: wurstmeister/kafka
    container_name: broker2
    ports:
      - "9093:9092"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - broker1
    environment:
      KAFKA_LOG_DIRS: /var/log/kafka
      KAFKA_BROKER_ID: 2
      KAFKA_CREATE_TOPICS: BTC:1:3,ETH:1:3
      KAFKA_ADVERTISED_HOST_NAME: docker-nitrohsu.com
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181
      restart: always  
  broker3: 
    image: wurstmeister/kafka
    container_name: broker3
    ports:
      - "9094:9092"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - broker2
    environment:
      KAFKA_LOG_DIRS: /var/log/kafka
      KAFKA_BROKER_ID: 3
      KAFKA_CREATE_TOPICS: BTC:1:3,ETH:1:3
      KAFKA_ADVERTISED_HOST_NAME: docker-nitrohsu.com
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181
      restart: always  
